<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductosSeeder extends Seeder
{
    public function run(): void
    {

        Producto::create([
                'guid' => 'G4YXT9K5QLV',
                'vendedor_id' => 1,
                'nombre' => 'Portátil Gamer',
                'descripcion' => 'Este potente portátil está diseñado para gaming de alto rendimiento y tareas exigentes como edición de video y modelado 3D. Equipado con un procesador de última generación, tarjeta gráfica dedicada y una pantalla de alta frecuencia de actualización, ofrece una experiencia fluida tanto para jugadores como para profesionales.',
                'estadoFisico' => 'Nuevo',
                'precio' => 800.00,
                'stock' => 100,
                'categoria' => 'Tecnologia',
                'estado' => 'Disponible',
                'imagenes' => ['productos/portatil1.webp', 'productos/portatil2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'Z8K3VLYTQ72',
                'vendedor_id' => 2,
                'nombre' => 'Chaqueta de Cuero',
                'descripcion' => 'Chaqueta de cuero genuino con un diseño clásico y sofisticado. Ideal para quienes buscan un look elegante sin sacrificar comodidad y protección contra el frío. Su forro interior aporta calidez, mientras que su material resistente garantiza una larga durabilidad.',
                'estadoFisico' => 'Usado',
                'precio' => 15.00,
                'stock' => 100,
                'categoria' => 'Ropa',
                'estado' => 'Disponible',
                'imagenes' => ['productos/chaqueta1.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'QX9T7LK5VY3',
                'vendedor_id' =>3,
                'nombre' => 'Guitarra Eléctrica',
                'descripcion' => 'Guitarra eléctrica de cuerpo sólido con un diseño clásico y un sonido potente. Perfecta para músicos de cualquier nivel que buscan un instrumento versátil para rock, blues, jazz y más. Aunque presenta signos de uso, su sonido sigue siendo excepcional y está lista para conectar y tocar.',
                'estadoFisico' => 'Deteriorado',
                'precio' => 300.00,
                'stock' => 100,
                'categoria' => 'Musica',
                'estado' => 'Disponible',
                'imagenes' => ['productos/guitarra1.webp', 'productos/guitarra2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'VYQ8XK4T9L5',
                'vendedor_id' => 1,
                'nombre' => 'Pantalones Vaqueros',
                'descripcion' => 'Pantalones vaqueros de alta calidad, confeccionados con tela resistente y un ajuste cómodo. Ideales para el día a día o para combinarlos con distintos estilos. Su diseño clásico nunca pasa de moda y su durabilidad los hace una opción excelente para cualquier guardarropa.',
                'estadoFisico' => 'Nuevo',
                'precio' => 10.00,
                'stock' => 100,
                'categoria' => 'Ropa',
                'estado' => 'Disponible',
                'imagenes' => ['productos/pantalones1.webp', 'productos/pantalones2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'T3K9QLYV7X5',
                'vendedor_id' => 2,
                'nombre' => 'Mario Party 8',
                'descripcion' => 'Divertido juego de fiesta para toda la familia. Mario Party 8 ofrece una gran variedad de minijuegos y tableros interactivos que garantizan horas de entretenimiento. Perfecto para jugar solo o en compañía de amigos y familiares, este título es un clásico de la saga de Nintendo.',
                'estadoFisico' => 'Nuevo',
                'precio' => 50.00,
                'stock' => 100,
                'categoria' => 'Videojuegos',
                'estado' => 'Disponible',
                'imagenes' => ['productos/mario1.webp','productos/mario2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'L5X7YQT9VK3',
                'vendedor_id' => 3,
                'nombre' => 'Consola Xbox Series X',
                'descripcion' => 'La consola de nueva generación de Microsoft con un rendimiento excepcional. Disfruta de gráficos en 4K, tiempos de carga ultrarrápidos y una biblioteca de juegos extensa. Ideal para quienes buscan la mejor experiencia en videojuegos y entretenimiento en casa.',
                'estadoFisico' => 'Nuevo',
                'precio' => 250.00,
                'stock' => 100,
                'categoria' => 'Videojuegos',
                'estado' => 'Disponible',
                'imagenes' => ['productos/xbox1.webp', 'productos/xbox2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'X8KQ5T9YLV7',
                'vendedor_id' => 2,
                'nombre' => 'Set de Púas para Guitarra',
                'descripcion' => 'Paquete de 12 púas de diferentes grosores y materiales, ideales para distintos estilos musicales. Perfectas para guitarras acústicas y eléctricas.',
                'estadoFisico' => 'Nuevo',
                'precio' => 5.00,
                'stock' => 100,
                'categoria' => 'Musica',
                'estado' => 'Disponible',
                'imagenes' => ['productos/puas1.webp', 'productos/puas2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'Y9VQXK37TL5',
                'vendedor_id' => 2,
                'nombre' => 'Amplificador Fender 40W',
                'descripcion' => 'Amplificador Fender de 40W con ecualización ajustable y efectos de reverberación. Ideal para ensayos y pequeñas presentaciones en vivo.',
                'estadoFisico' => 'Usado',
                'precio' => 120.00,
                'stock' => 100,
                'categoria' => 'Musica',
                'estado' => 'Disponible',
                'imagenes' => ['productos/ampli1.webp', 'productos/ampli2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'K7YLTQ9X5V3',
                'vendedor_id' => 1,
                'nombre' => 'Batería Electrónica Roland',
                'descripcion' => 'Kit de batería electrónica con pads sensibles al tacto, módulo de sonidos y conexión MIDI para grabaciones digitales.',
                'estadoFisico' => 'Nuevo',
                'precio' => 600.00,
                'stock' => 100,
                'categoria' => 'Musica',
                'estado' => 'Disponible',
                'imagenes' => ['productos/bateria1.webp', 'productos/bateria2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'QX5V9KY3TL7',
                'vendedor_id' => 3,
                'nombre' => 'Smartwatch Xiaomi Mi Band 7',
                'descripcion' => 'Reloj inteligente con monitor de actividad física, sensor de frecuencia cardíaca y notificaciones de smartphone.',
                'estadoFisico' => 'Nuevo',
                'precio' => 50.00,
                'stock' => 100,
                'categoria' => 'Tecnologia',
                'estado' => 'Disponible',
                'imagenes' => ['productos/smartwatch1.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'X9YT7KQLV53',
                'vendedor_id' => 3,
                'nombre' => 'Zapatillas Adidas Running',
                'descripcion' => 'Zapatillas deportivas con suela de espuma de alto rendimiento. Comodidad y soporte ideal para correr largas distancias.',
                'estadoFisico' => 'Nuevo',
                'precio' => 70.00,
                'stock' => 100,
                'categoria' => 'Ropa',
                'estado' => 'Disponible',
                'imagenes' => ['productos/zapatillas1.webp', 'productos/zapatillas2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => '7K5TQL9XYV3',
                'vendedor_id' => 2,
                'nombre' => 'Lámpara LED Inteligente',
                'descripcion' => 'Lámpara de escritorio con luz LED regulable y control táctil. Compatible con asistentes de voz como Alexa y Google Home.',
                'estadoFisico' => 'Nuevo',
                'precio' => 30.00,
                'stock' => 100,
                'categoria' => 'Hogar',
                'estado' => 'Disponible',
                'imagenes' => ['productos/lampara1.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'TQ9K7XY5LV3',
                'vendedor_id' => 1,
                'nombre' => 'The Legend of Zelda: Breath of the Wild',
                'descripcion' => 'Juego de aventura y exploración para Nintendo Switch con un mundo abierto enorme y mecánicas innovadoras.',
                'estadoFisico' => 'Nuevo',
                'precio' => 55.00,
                'stock' => 100,
                'categoria' => 'Videojuegos',
                'estado' => 'Disponible',
                'imagenes' => ['productos/zelda1.webp', 'productos/zelda2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'V3XKYQ9T57L',
                'vendedor_id' => 1,
                'nombre' => 'Colección de Blu-ray Star Wars',
                'descripcion' => 'Edición especial en Blu-ray de la saga completa de Star Wars, con contenido exclusivo y material detrás de cámaras.',
                'estadoFisico' => 'Usado',
                'precio' => 80.00,
                'stock' => 100,
                'categoria' => 'Cine',
                'estado' => 'Disponible',
                'imagenes' => ['productos/starwars1.webp', 'productos/starwars2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => '5KQYT79XLV3',
                'vendedor_id' => 3,
                'nombre' => 'Cafetera Espresso Automática',
                'descripcion' => 'Cafetera con molinillo integrado y sistema de espumado de leche. Perfecta para preparar café de calidad en casa.',
                'estadoFisico' => 'Nuevo',
                'precio' => 150.00,
                'stock' => 100,
                'categoria' => 'Cocina',
                'estado' => 'Disponible',
                'imagenes' => ['productos/cafetera1.webp', 'productos/cafetera2.webp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        Producto::create([
                'guid' => 'XK5VQT9Y3L7',
                'vendedor_id' => 1,
                'nombre' => 'Figura de Acción Spider-Man',
                'descripcion' => 'Figura coleccionable de Spider-Man en edición especial con detalles realistas y articulaciones móviles.',
                'estadoFisico' => 'Nuevo',
                'precio' => 40.00,
                'stock' => 100,
                'categoria' => 'Coleccionismo',
                'estado' => 'Disponible',
                'imagenes' => ['productos/spiderman1.webp'],
                'created_at' => now(),
                'updated_at' => now(),

        ]);

        $productos = [
            ['Silla Gamer Ergonómica', 'Hogar', 120.00, 'Nuevo'],
            ['Teclado Mecánico RGB', 'Tecnologia', 60.00, 'Nuevo'],
            ['Smart TV 55" 4K', 'Tecnologia', 500.00, 'Nuevo'],
            ['Auriculares Bluetooth', 'Tecnologia', 35.00, 'Nuevo'],
            ['Bicicleta de Montaña', 'Deporte', 300.00, 'Nuevo'],
            ['Mochila de Senderismo 60L', 'Otros', 70.00, 'Nuevo'],
            ['Juego de Ollas de Acero Inoxidable', 'Hogar', 90.00, 'Nuevo'],
            ['Robot Aspirador Inteligente', 'Hogar', 250.00, 'Nuevo'],
            ['Cámara Réflex Canon', 'Tecnologia', 400.00, 'Usado'],
            ['Patinete Eléctrico', 'Tecnologia', 350.00, 'Nuevo'],
            ['Reloj Casio Vintage', 'Ropa', 30.00, 'Nuevo'],
            ['Mesa de Oficina Ajustable', 'Hogar', 200.00, 'Nuevo'],
            ['Monitor Gaming 144Hz', 'Tecnologia', 180.00, 'Nuevo'],
            ['Cojín Ortopédico para Silla', 'Hogar', 25.00, 'Nuevo'],
            ['Guitarra Electrica Acoustica', 'Musica', 150.00, 'Nuevo'],
            ['Batería Portátil 12V', 'Tecnologia', 50.00, 'Nuevo'],
            ['Disco Duro SSD 256GB', 'Tecnologia', 120.00, 'Nuevo'],
            ['Mouse Gaming Logitech', 'Tecnologia', 45.00, 'Nuevo'],
            ['Teclado Gaming Logitech', 'Tecnologia', 55.00, 'Nuevo'],
            ['Cargador Portátil 100W', 'Tecnologia', 30.00, 'Nuevo'],
            ['Pantalla LED 4K', 'Tecnologia', 150.00, 'Nuevo'],
            ['Smartwatch Apple Watch', 'Tecnologia', 120.00, 'Nuevo'],
            ['Smart TV Samsung SmartThings', 'Tecnologia', 250.00, 'Nuevo'],
            ['Auriculares Bluetooth Sony', 'Tecnologia', 40.00, 'Nuevo'],
            ['Reloj Digital Philips', 'Ropa', 25.00, 'Nuevo'],
            ['Mesa de Cocina Inglesa', 'Hogar', 250.00, 'Nuevo'],
            ['Silla de Escritorio', 'Hogar', 150.00, 'Nuevo'],
            ['Pantalla LED 27" Full HD', 'Tecnologia', 100.00, 'Nuevo'],
            ['Smartwatch Apple Watch Series 6', 'Tecnologia', 180.00, 'Nuevo'],
            ['Smart TV Samsung SmartThings 3', 'Tecnologia', 300.00, 'Nuevo'],
            ['Auriculares Bluetooth Panasonic', 'Tecnologia', 50.00, 'Nuevo'],
            ['Reloj Digital Philips 4K', 'Ropa', 30.00, 'Nuevo'],
            ['Mesa de Cocina Ergonómica', 'Hogar', 200.00, 'Nuevo'],
            ['Silla de Escritorio Ergonómica', 'Hogar', 150.00, 'Nuevo'],
        ];

        foreach ($productos as $producto) {
            Producto::create([
                'guid' => Str::upper(Str::random(11)),
                'vendedor_id' => rand(4, 12),
                'nombre' => $producto[0],
                'descripcion' => 'Descripción de ' . $producto[0],
                'estadoFisico' => $producto[3],
                'precio' => $producto[2],
                'stock' => rand(10, 100),
                'categoria' => $producto[1],
                'estado' => 'Disponible',
                'imagenes' => ['productos/producto.webp'],
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(7),
            ]);
        }
    }
}
